# Generated by Django 4.2.3 on 2023-07-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Balance',
            field=models.IntegerField(default=1000),
        ),
    ]
