# Generated by Django 4.2.3 on 2023-07-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePage', '0002_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pnumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
