# Generated by Django 4.2.3 on 2023-07-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePage', '0003_account_pnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pnumber',
            new_name='Phone_Number',
        ),
    ]
